#!/bin/bash

###############################################################
#          jupyter/jupyterlab extensions/kernels              #
###############################################################

# Building everything up
echo "Building everything up (jupyter lab build)"
jupyter lab build --dev-build


###############################################################
#             moving to a local installation folder           #
###############################################################

mkdir -p ~/resources/local
cd    ~/resources/local


###############################################################
#            mariadb installation commands                    #
###############################################################

# Definir a versão do MariaDB
export MARIADB_VERSION=10.5.9
echo "export MARIADB_VERSION=${MARIADB_VERSION}" >> ~/.bashrc
echo "export MARIADB_VERSION=${MARIADB_VERSION}" >> ~/.profile

# Definir o diretório de instalação do MariaDB
export MARIADB_HOME=$(pwd)/mariadb-${MARIADB_VERSION}
echo "export MARIADB_HOME=${MARIADB_HOME}"       >> ~/.bashrc
echo "export MARIADB_HOME=${MARIADB_HOME}"       >> ~/.profile

# Baixar e instalar o MariaDB
wget https://downloads.mariadb.org/f/mariadb-${MARIADB_VERSION}/source/mariadb-${MARIADB_VERSION}.tar.gz -q && \
tar -xvf mariadb-${MARIADB_VERSION}.tar.gz >/dev/null                                                      && \
rm       mariadb-${MARIADB_VERSION}.tar.gz                                                                 && \
mv       mariadb-${MARIADB_VERSION} mariadb-${MARIADB_VERSION}

# Adicionar os binários ao $PATH
echo "export PATH=\$PATH:\$MARIADB_HOME/bin"  >> ~/.bashrc
echo "export PATH=\$PATH:\$MARIADB_HOME/bin"  >> ~/.profile


###############################################################
#                 redis installation commands                 #
###############################################################

export REDIS_VERSION=6.0.5
echo "export REDIS_VERSION=${REDIS_VERSION}" >> ~/.bashrc
echo "export REDIS_VERSION=${REDIS_VERSION}" >> ~/.profile

export REDIS_HOME=$(pwd)/redis-${REDIS_VERSION}
echo "export REDIS_HOME=${REDIS_HOME}"       >> ~/.bashrc
echo "export REDIS_HOME=${REDIS_HOME}"       >> ~/.profile

wget http://download.redis.io/releases/redis-${REDIS_VERSION}.tar.gz  && \
tar xvzf redis-${REDIS_VERSION}.tar.gz                                && \
rm       redis-${REDIS_VERSION}.tar.gz                                && \
cd       redis-${REDIS_VERSION}
make

mkdir bin
cp src/redis-server bin/
cp src/redis-cli bin/

echo "export PATH=\$PATH:\$REDIS_HOME/bin"   >> ~/.bashrc
echo "export PATH=\$PATH:\$REDIS_HOME/bin"   >> ~/.profile


###############################################################
#                 git clone commands                          #
###############################################################

# Clonar um repositório, caso necessário
git clone --recursive https://github.com/RedisTimeSeries/RedisTimeSeries.git
cd RedisTimeSeries
./sbin/setup
bash -l
make
make run -n


###############################################################
#                 finalizing installation                     #
###############################################################

# Carregar as variáveis de ambiente
source ~/.bashrc
source ~/.profile

echo "Installation complete. MariaDB, Redis, and JupyterLab are ready to use."
