#!/bin/bash

# Exibe uma mensagem de status
echo "Iniciando o ambiente de trabalho..."

# Garante que os pacotes necessários estão instalados
source ~/.bashrc

# (Opcional) Certifique-se de que o Redis esteja rodando, se necessário para testes locais
# redis-server &

# Use MariaDB remoto (ajuste os detalhes no script Python)
echo "Certifique-se de que o MariaDB remoto esteja configurado corretamente."

# Iniciar o JupyterLab
jupyter lab
