version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    container_name: epinga_maridadb
    environment:
      MARIADB_ROOT_PASSWORD: epinga_db_master_password
      MARIADB_DATABASE: epinga_db
      MARIADB_USER: epinga_db_user
      MARIADB_PASSWORD: epinga_db_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:latest
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: epinga_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mariadb_data:
  redis_data:
