version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: epinga_mariadb
    environment:
      MARIADB_ROOT_PASSWORD: epinga_db_master_password
      MARIADB_DATABASE: epinga_db
      MARIADB_USER: epinga_db_user
      MARIADB_PASSWORD: epinga_db_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: epinga_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  jupyter:
    build:
      context: ./jupyter
    container_name: epinga_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work  
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    depends_on:
      - mariadb
      - redis    

volumes:
  mariadb_data:
  redis_data:
